services:
  app:
    container_name: node-encurtador-url
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  app_node_modules:
  postgres_data:
